diff --git a/Makefile b/Makefile
index cb38dc8a9..08d5001cd 100644
--- a/Makefile
+++ b/Makefile
@@ -44,7 +44,7 @@ bin/pardot-test-srv: bin/salesforce-test-srv
 
 build_cmds: | $(OBJDIR)
 	echo $(OBJECTS)
-	GOBIN=$(OBJDIR) go install -mod=vendor $(GO_BUILD_FLAGS) ./...
+	GOBIN=$(OBJDIR) go install -mod=vendor -buildvcs=false $(GO_BUILD_FLAGS) ./...
 
 # Building a .deb requires `fpm` from https://github.com/jordansissel/fpm
 # which you can install with `gem install fpm`.
