#!/usr/bin/env bash

set -e

TODAY=`date '+%Y_%m_%d'`
LOGFILE=/logs/cron-mailer.log
echo $TODAY >>$LOGFILE

cd /home/labca/boulder
docker-compose exec -T boulder bin/expiration-mailer --config labca/config/expiration-mailer.json >>$LOGFILE 2>&1
