#!/usr/bin/env bash

set -e

TODAY=`date '+%Y_%m_%d'`
echo "Running cron-mailer for ${TODAY}..."

cd /home/labca/boulder
docker-compose exec -T boulder bin/expiration-mailer --config labca/config/expiration-mailer.json 2>&1
