#!/usr/bin/env bash

set -e

cd /home/labca/nginx_data/ssl
date >> acme_tiny.log
python ~labca/acme_tiny.py --account-key ./account.key --csr ./domain.csr --acme-dir /home/labca/nginx_data/static/.well-known/acme-challenge/ > domain_chain.crt 2>> acme_tiny.log || exit 1
mv domain_chain.crt labca_cert.pem

cd /home/labca/boulder
docker-compose restart nginx
