#!/usr/bin/env bash

set -e

cd /etc/nginx/ssl
echo >> acme_tiny.log
date >> acme_tiny.log
python3 /labca/acme_tiny.py --account-key ./account.key --csr ./domain.csr --acme-dir /var/www/html/.well-known/acme-challenge/ > domain_chain.crt 2> >(tee -a acme_tiny.log >&2) || exit 1
mv domain_chain.crt labca_cert.pem

cd /boulder
docker-compose restart nginx
