#!/usr/bin/env bash

set -e

baseDir=$(cd $(dirname $0) && pwd)
dataDir="$baseDir/data"

export PKI_ROOT_CERT_BASE="$dataDir/root-ca"
export PKI_INT_CERT_BASE="$dataDir/issuer/ca-int"

cd /opt/wwwstatic

$baseDir/apply-nginx

cp $PKI_ROOT_CERT_BASE.crl crl/
cp $PKI_ROOT_CERT_BASE.pem certs/
cp $PKI_ROOT_CERT_BASE.der certs/
cp $PKI_INT_CERT_BASE.pem certs/
cp $PKI_INT_CERT_BASE.der certs/


cd /opt/boulder/labca
$baseDir/apply-boulder
